### ISSUE TITLE
CUDA out of Memory

### ISSUE THREAD

**Issue by PhilipCheungISAB** [IsshikiHugh/HSMR#5]
Dear @IsshikiHugh ,

Thank you for replying on previous issue. I'm installing Ubuntu in my laptop to ensure smooth environment builds.
I found another issue as below

My portable RTX 3060 6GB seems not possible to run this project. I got continous CUDA out of memory. I tried reducing bet_mis to 128, --max_instances 1, still the same issue.
Good news is I can run with CPU slowly.

Could you sugguest some solutions to use my GPU?

> [04/06 03:01:31][INFO] [Checkpointer] Loading from /home/philipcheung/.torch/iopath_cache/detectron2/ViTDet/COCO/cascade_mask_rcnn_vitdet_h/f328730692/model_final_f05665.pkl ...
> [04/06 03:01:32][INFO] Reading a file from 'Detectron2 ViTDet Model Zoo'
> [04/06 03:01:32][INFO] [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(1024, 1024), max_size=1024)]
> [04/06 03:01:32][INFO] 🖼️ Detecting...
> Batch Detection:   0%|                                    | 0/7 [00:00<?, ?it/s][04/06 03:01:33][ERROR] Image No.0: CUDA out of memory. Tried to allocate 412.00 MiB. GPU 0 has a total capacity of 5.79 GiB of which 171.56 MiB is free. Including non-PyTorch memory, this process has 4.81 GiB memory in use. Of the allocated memory 4.47 GiB is allocated by PyTorch, and 204.10 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.
> [04/06 03:01:33][INFO] Adjust the batch size to 5.
> [04/06 03:01:33][ERROR] Image No.0: CUDA out of memory. Tried to allocate 294.00 MiB. GPU 0 has a total capacity of 5.79 GiB of which 159.56 MiB is free. Including non-PyTorch memory, this process has 4.82 GiB memory in use. Of the allocated memory 3.95 GiB is allocated by PyTorch, and 749.35 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.
> [04/06 03:01:33][INFO] Adjust the batch size to 3.
> [04/06 03:01:34][ERROR] Image No.0: CUDA out of memory. Tried to allocate 3.00 GiB. GPU 0 has a total capacity of 5.79 GiB of which 1.14 GiB is free. Including non-PyTorch memory, this process has 3.83 GiB memory in use. Of the allocated memory 3.21 GiB is allocated by PyTorch, and 498.74 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.
> [04/06 03:01:34][INFO] Adjust the batch size to 2.
> [04/06 03:01:34][ERROR] Image No.0: CUDA out of memory. Tried to allocate 2.00 GiB. GPU 0 has a total capacity of 5.79 GiB of which 1.54 GiB is free. Including non-PyTorch memory, this process has 3.43 GiB memory in use. Of the allocated memory 3.03 GiB is allocated by PyTorch, and 278.74 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.
> [04/06 03:01:34][INFO] Adjust the batch size to 1.
> [04/06 03:01:35][ERROR] Image No.0: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 5.79 GiB of which 849.56 MiB is free. Including non-PyTorch memory, this process has 4.14 GiB memory in use. Of the allocated memory 3.79 GiB is allocated by PyTorch, and 222.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.
> [04/06 03:01:35][ERROR] Can't afford image No.0 even with batch_size=1, skip.
> [04/06 03:01:35][ERROR] Image No.1: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 5.79 GiB of which 849.56 MiB is free. Including non-PyTorch memory, this process has 4.14 GiB memory in use. Of the allocated memory 3.79 GiB is allocated by PyTorch, and 222.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.

**Comment by IsshikiHugh** [comment]
Hi, thank you for being interested in HSMR!

The problem is caused by the detector in the preprocessing stage. You have already found the related options.

Regarding this, you can try keep reducing the `bet_mis` and see whether it influences the result significantly. If not, that would be great.

If the detectron detector fails in that case, you might want to try other detectors like [mmdet](https://github.com/open-mmlab/mmdetection) or you can extract the bounding box from the ground truth vertices projection (if you have).

Sorry for the inconvenience! Thank you!

**Comment by migeee8** [comment]
I got the same issue.
`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.79 GiB. GPU 0 has a total capacity of 23.68 GiB of which 450.69 MiB is free. Process 28262 has 23.24 GiB memory in use. Of the allocated memory 14.55 GiB is allocated by PyTorch, and 8.38 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

I'm running this code on a remote server with 2 GPUs (both are RTX 3090). I wonder if I can run this code on multi-GPU mode. 
I'm still new to this, so I apologize if this is a basic question - but I'd really appreciate some guidance on how to properly utilize both GPUs for this task.

**Comment by IsshikiHugh** [comment]
> I got the same issue. `torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.79 GiB. GPU 0 has a total capacity of 23.68 GiB of which 450.69 MiB is free. Process 28262 has 23.24 GiB memory in use. Of the allocated memory 14.55 GiB is allocated by PyTorch, and 8.38 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`
> 
> I'm running this code on a remote server with 2 GPUs (both are RTX 3090). I wonder if I can run this code on multi-GPU mode. I'm still new to this, so I apologize if this is a basic question - but I'd really appreciate some guidance on how to properly utilize both GPUs for this task.

Hi! Thank you for being interested in HSMR! Don't worry about that, I am willing to offer help.

I have tested the memory cost locally, and it requires at most 28,975MiB with default settings. And it seems like you have only 23.68GiB, which is insufficient.
My advices are similar, 1) use CPU to detect the human bounding box; 2) modify detector; 3) use our colab demo [here](https://colab.research.google.com/drive/1RDA9iKckCDKh_bbaKjO8bQ0-Lv5fw1CB?usp=sharing); 4) input the bounding box yourself.

**Comment by PhilipCheungISAB** [comment]
Hey @IsshikiHugh 

Thank you. It's strange that when I switch back to Windows from Ubuntu, my 6GB vram is working when auto adjusting batch size to 5...
Problem fixed, haha!

> [04/09 10:58:15][INFO] [Checkpointer] Loading from C:\Users\PhilipCheung/.torch/iopath_cache\detectron2/ViTDet/COCO/cascade_mask_rcnn_vitdet_h/f328730692\model_final_f05665.pkl ...
> [04/09 10:58:16][INFO] Reading a file from 'Detectron2 ViTDet Model Zoo'
> [04/09 10:58:17][INFO] [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(1024, 1024), max_size=1024)]
> [04/09 10:58:18][INFO] 🖼️ Detecting...
> Batch Detection:   0%|                                                                           | 0/7 [00:00<?, ?it/s][04/09 10:58:29][ERROR] Image No.0: CUDA out of memory. Tried to allocate 7.00 GiB. GPU 0 has a total capacity of 6.00 GiB of which 0 bytes is free. Of the allocated memory 18.05 GiB is allocated by PyTorch, and 310.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.
> [04/09 10:58:29][INFO] Adjust the batch size to 5.
> E:\Software\anaconda3\envs\hsmr\lib\site-packages\torch\functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3610.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> Batch Detection: 100%|███████████████████████████████████████████████████████████████████| 7/7 [00:41<00:00,  5.97s/it]
> 100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 233.32it/s]
> [04/09 10:58:59][INFO] 🔍 Totally 7 human instances are detected.
> [04/09 10:58:59][INFO] 🧱 Building recovery pipeline.
> [04/09 10:59:00][INFO] Building inference pipeline of HSMR-train-vit_h-Oct21
> [04/09 10:59:00 @ __init__ @ /lib\body_models\skel_wrapper.py:73][INFO] Using customized joint regressor.
> e:\docker\hsmr\lib\modeling\pipelines\hsmr.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>   pipeline.load_state_dict(torch.load(ckpt_fn, map_location=device)['state_dict'])
> [04/09 10:59:04][INFO] Load checkpoint from data_inputs\released_models\HSMR-ViTH-r1d1\checkpoints\hsmr.ckpt.
> [04/09 10:59:05][INFO] 🏃 Recovering with B=300...
> 100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.29s/it]
> [04/09 10:59:14][INFO] 🤌 Preparing meshes...
> 100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 34.98it/s]
> [04/09 10:59:14][INFO] 🏁 Done.
> Rendering: 100%|█████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.39it/s]
> Saving images: 100%|█████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 88.92it/s]
> [04/09 10:59:19][INFO] 🎨 Rendering results are under e:\docker\hsmr\data_outputs\demos.
> [04/09 10:59:19][INFO] 🎊 Everything is done!
> [EA-G] main @ /E:\Docker\HSMR\exp\run_demo.py:86 -> global efficiency analysis:
>         Data-Preprocessing/Load-Inputs: 0.28 sec
>         Data-Preprocessing/Detector-Initialization: 7.15 sec
>         Data-Preprocessing/Detecting: 41.86 sec
>         Data-Preprocessing/Patching-&-Loading: 0.03 sec
>         Data-Preprocessing: 49.34 sec
>         Pipeline-Initialization: 5.10 sec
>         Recovery: 9.43 sec
>         Visualization: 5.12 sec

**Comment by IsshikiHugh** [comment]
> Hey [@IsshikiHugh](https://github.com/IsshikiHugh)
> 
> Thank you. It's strange that when I switch back to Windows from Ubuntu, my 6GB vram is working when auto adjusting batch size to 5... Problem fixed, haha!
> 
> > [04/09 10:58:15][INFO] [Checkpointer] Loading from C:\Users\PhilipCheung/.torch/iopath_cache\detectron2/ViTDet/COCO/cascade_mask_rcnn_vitdet_h/f328730692\model_final_f05665.pkl ...
> > [04/09 10:58:16][INFO] Reading a file from 'Detectron2 ViTDet Model Zoo'
> > [04/09 10:58:17][INFO] [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(1024, 1024), max_size=1024)]
> > [04/09 10:58:18][INFO] 🖼️ Detecting...
> > Batch Detection:   0%|                                                                           | 0/7 [00:00<?, ?it/s][04/09 10:58:29][ERROR] Image No.0: CUDA out of memory. Tried to allocate 7.00 GiB. GPU 0 has a total capacity of 6.00 GiB of which 0 bytes is free. Of the allocated memory 18.05 GiB is allocated by PyTorch, and 310.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables). Try to fix it.
> > [04/09 10:58:29][INFO] Adjust the batch size to 5.
> > E:\Software\anaconda3\envs\hsmr\lib\site-packages\torch\functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3610.)
> > return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> > Batch Detection: 100%|███████████████████████████████████████████████████████████████████| 7/7 [00:41<00:00,  5.97s/it]
> > 100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 233.32it/s]
> > [04/09 10:58:59][INFO] 🔍 Totally 7 human instances are detected.
> > [04/09 10:58:59][INFO] 🧱 Building recovery pipeline.
> > [04/09 10:59:00][INFO] Building inference pipeline of HSMR-train-vit_h-Oct21
> > [04/09 10:59:00 @ **init** @ /lib\body_models\skel_wrapper.py:73][INFO] Using customized joint regressor.
> > e:\docker\hsmr\lib\modeling\pipelines\hsmr.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
> > pipeline.load_state_dict(torch.load(ckpt_fn, map_location=device)['state_dict'])
> > [04/09 10:59:04][INFO] Load checkpoint from data_inputs\released_models\HSMR-ViTH-r1d1\checkpoints\hsmr.ckpt.
> > [04/09 10:59:05][INFO] 🏃 Recovering with B=300...
> > 100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.29s/it]
> > [04/09 10:59:14][INFO] 🤌 Preparing meshes...
> > 100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 34.98it/s]
> > [04/09 10:59:14][INFO] 🏁 Done.
> > Rendering: 100%|█████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.39it/s]
> > Saving images: 100%|█████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 88.92it/s]
> > [04/09 10:59:19][INFO] 🎨 Rendering results are under e:\docker\hsmr\data_outputs\demos.
> > [04/09 10:59:19][INFO] 🎊 Everything is done!
> > [EA-G] main @ /E:\Docker\HSMR\exp\run_demo.py:86 -> global efficiency analysis:
> > Data-Preprocessing/Load-Inputs: 0.28 sec
> > Data-Preprocessing/Detector-Initialization: 7.15 sec
> > Data-Preprocessing/Detecting: 41.86 sec
> > Data-Preprocessing/Patching-&-Loading: 0.03 sec
> > Data-Preprocessing: 49.34 sec
> > Pipeline-Initialization: 5.10 sec
> > Recovery: 9.43 sec
> > Visualization: 5.12 sec

Oh, that's interesting! I'm glad that my batch-size auto-adjustment tools help! 🎊

**Comment by PhilipCheungISAB** [comment]
I guess the shared GPU memory is helping a lot here, but not available in Ubuntu.

![Image](https://github.com/user-attachments/assets/3d8f1740-33f7-4bd0-8f12-d75aed029248)
